"""
Arma → atributo de ataque e dado de dano (SRD 5.1).

GERADO por `ingestor/gerar_tabela_armas.py` — NÃO editar à mão.
Existe porque a ficha não tinha conceito de arma, e sem ele o Mestre
anunciava o atributo do ataque por vibe (playtest 10/08: pediu Força a
um Ranger de arco).
"""

from typing import Any

ARMAS: dict[str, dict[str, Any]] = {'battleaxe': {'atributo': 'FOR',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Battleaxe',
               'nomes_pt': ['machado de batalha', 'machado']},
 'blowgun': {'atributo': 'DES',
             'dado': '1',
             'distancia': True,
             'nome_en': 'Blowgun',
             'nomes_pt': []},
 'club': {'atributo': 'FOR',
          'dado': '1d4',
          'distancia': False,
          'nome_en': 'Club',
          'nomes_pt': ['clava', 'porrete']},
 'crossbow-hand': {'atributo': 'DES',
                   'dado': '1d6',
                   'distancia': True,
                   'nome_en': 'Crossbow, hand',
                   'nomes_pt': []},
 'crossbow-heavy': {'atributo': 'DES',
                    'dado': '1d10',
                    'distancia': True,
                    'nome_en': 'Crossbow, heavy',
                    'nomes_pt': []},
 'crossbow-light': {'atributo': 'DES',
                    'dado': '1d8',
                    'distancia': True,
                    'nome_en': 'Crossbow, light',
                    'nomes_pt': []},
 'dagger': {'atributo': 'MELHOR',
            'dado': '1d4',
            'distancia': False,
            'nome_en': 'Dagger',
            'nomes_pt': ['adaga', 'punhal']},
 'dart': {'atributo': 'MELHOR',
          'dado': '1d4',
          'distancia': True,
          'nome_en': 'Dart',
          'nomes_pt': []},
 'flail': {'atributo': 'FOR',
           'dado': '1d8',
           'distancia': False,
           'nome_en': 'Flail',
           'nomes_pt': ['mangual']},
 'glaive': {'atributo': 'FOR',
            'dado': '1d10',
            'distancia': False,
            'nome_en': 'Glaive',
            'nomes_pt': ['glaive']},
 'greataxe': {'atributo': 'FOR',
              'dado': '1d12',
              'distancia': False,
              'nome_en': 'Greataxe',
              'nomes_pt': ['machado grande']},
 'greatclub': {'atributo': 'FOR',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Greatclub',
               'nomes_pt': []},
 'greatsword': {'atributo': 'FOR',
                'dado': '2d6',
                'distancia': False,
                'nome_en': 'Greatsword',
                'nomes_pt': ['espada grande', 'montante']},
 'halberd': {'atributo': 'FOR',
             'dado': '1d10',
             'distancia': False,
             'nome_en': 'Halberd',
             'nomes_pt': ['alabarda']},
 'handaxe': {'atributo': 'FOR',
             'dado': '1d6',
             'distancia': False,
             'nome_en': 'Handaxe',
             'nomes_pt': ['machadinha']},
 'javelin': {'atributo': 'FOR',
             'dado': '1d6',
             'distancia': False,
             'nome_en': 'Javelin',
             'nomes_pt': ['azagaia']},
 'lance': {'atributo': 'FOR',
           'dado': '1d12',
           'distancia': False,
           'nome_en': 'Lance',
           'nomes_pt': []},
 'light-hammer': {'atributo': 'FOR',
                  'dado': '1d4',
                  'distancia': False,
                  'nome_en': 'Light hammer',
                  'nomes_pt': []},
 'longbow': {'atributo': 'DES',
             'dado': '1d8',
             'distancia': True,
             'nome_en': 'Longbow',
             'nomes_pt': ['arco longo', 'arco']},
 'longsword': {'atributo': 'FOR',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Longsword',
               'nomes_pt': ['espada longa', 'espada']},
 'mace': {'atributo': 'FOR',
          'dado': '1d6',
          'distancia': False,
          'nome_en': 'Mace',
          'nomes_pt': ['maça']},
 'maul': {'atributo': 'FOR', 'dado': '2d6', 'distancia': False, 'nome_en': 'Maul', 'nomes_pt': []},
 'morningstar': {'atributo': 'FOR',
                 'dado': '1d8',
                 'distancia': False,
                 'nome_en': 'Morningstar',
                 'nomes_pt': []},
 'net': {'atributo': 'DES', 'dado': '1d4', 'distancia': True, 'nome_en': 'Net', 'nomes_pt': []},
 'pike': {'atributo': 'FOR',
          'dado': '1d10',
          'distancia': False,
          'nome_en': 'Pike',
          'nomes_pt': ['pique']},
 'quarterstaff': {'atributo': 'FOR',
                  'dado': '1d6',
                  'distancia': False,
                  'nome_en': 'Quarterstaff',
                  'nomes_pt': ['bordão', 'cajado']},
 'rapier': {'atributo': 'MELHOR',
            'dado': '1d8',
            'distancia': False,
            'nome_en': 'Rapier',
            'nomes_pt': ['rapieira', 'florete']},
 'scimitar': {'atributo': 'MELHOR',
              'dado': '1d6',
              'distancia': False,
              'nome_en': 'Scimitar',
              'nomes_pt': ['cimitarra']},
 'shortbow': {'atributo': 'DES',
              'dado': '1d6',
              'distancia': True,
              'nome_en': 'Shortbow',
              'nomes_pt': ['arco curto']},
 'shortsword': {'atributo': 'MELHOR',
                'dado': '1d6',
                'distancia': False,
                'nome_en': 'Shortsword',
                'nomes_pt': ['espada curta']},
 'sickle': {'atributo': 'FOR',
            'dado': '1d4',
            'distancia': False,
            'nome_en': 'Sickle',
            'nomes_pt': ['foice']},
 'sling': {'atributo': 'DES',
           'dado': '1d4',
           'distancia': True,
           'nome_en': 'Sling',
           'nomes_pt': ['funda']},
 'spear': {'atributo': 'FOR',
           'dado': '1d6',
           'distancia': False,
           'nome_en': 'Spear',
           'nomes_pt': ['lança']},
 'trident': {'atributo': 'FOR',
             'dado': '1d6',
             'distancia': False,
             'nome_en': 'Trident',
             'nomes_pt': ['tridente']},
 'war-pick': {'atributo': 'FOR',
              'dado': '1d8',
              'distancia': False,
              'nome_en': 'War pick',
              'nomes_pt': []},
 'warhammer': {'atributo': 'FOR',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Warhammer',
               'nomes_pt': ['martelo de guerra', 'martelo']},
 'whip': {'atributo': 'MELHOR',
          'dado': '1d4',
          'distancia': False,
          'nome_en': 'Whip',
          'nomes_pt': ['chicote']}}
