"""
Arma → atributo de ataque e dado de dano (SRD 5.1).

GERADO por `ingestor/gerar_tabela_armas.py` — NÃO editar à mão.
Existe porque a ficha não tinha conceito de arma, e sem ele o Mestre
anunciava o atributo do ataque por vibe (playtest 10/08: pediu Força a
um Ranger de arco).

`categoria` (simples/marcial) entrou em 17/08 para a ficha poder OFERECER
as armas válidas de uma escolha do SRD em vez de pedir texto livre.
"""

from typing import Any

ARMAS: dict[str, dict[str, Any]] = {'battleaxe': {'atributo': 'FOR',
               'categoria': 'marcial',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Battleaxe',
               'nomes_pt': ['machado de batalha', 'machado']},
 'blowgun': {'atributo': 'DES',
             'categoria': 'marcial',
             'dado': '1',
             'distancia': True,
             'nome_en': 'Blowgun',
             'nomes_pt': ['zarabatana']},
 'club': {'atributo': 'FOR',
          'categoria': 'simples',
          'dado': '1d4',
          'distancia': False,
          'nome_en': 'Club',
          'nomes_pt': ['clava', 'porrete']},
 'crossbow-hand': {'atributo': 'DES',
                   'categoria': 'marcial',
                   'dado': '1d6',
                   'distancia': True,
                   'nome_en': 'Crossbow, hand',
                   'nomes_pt': ['besta de mão']},
 'crossbow-heavy': {'atributo': 'DES',
                    'categoria': 'marcial',
                    'dado': '1d10',
                    'distancia': True,
                    'nome_en': 'Crossbow, heavy',
                    'nomes_pt': ['besta pesada']},
 'crossbow-light': {'atributo': 'DES',
                    'categoria': 'simples',
                    'dado': '1d8',
                    'distancia': True,
                    'nome_en': 'Crossbow, light',
                    'nomes_pt': ['besta leve', 'besta']},
 'dagger': {'atributo': 'MELHOR',
            'categoria': 'simples',
            'dado': '1d4',
            'distancia': False,
            'nome_en': 'Dagger',
            'nomes_pt': ['adaga', 'punhal']},
 'dart': {'atributo': 'MELHOR',
          'categoria': 'simples',
          'dado': '1d4',
          'distancia': True,
          'nome_en': 'Dart',
          'nomes_pt': ['dardo']},
 'flail': {'atributo': 'FOR',
           'categoria': 'marcial',
           'dado': '1d8',
           'distancia': False,
           'nome_en': 'Flail',
           'nomes_pt': ['mangual']},
 'glaive': {'atributo': 'FOR',
            'categoria': 'marcial',
            'dado': '1d10',
            'distancia': False,
            'nome_en': 'Glaive',
            'nomes_pt': ['glaive']},
 'greataxe': {'atributo': 'FOR',
              'categoria': 'marcial',
              'dado': '1d12',
              'distancia': False,
              'nome_en': 'Greataxe',
              'nomes_pt': ['machado grande']},
 'greatclub': {'atributo': 'FOR',
               'categoria': 'simples',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Greatclub',
               'nomes_pt': ['clava grande']},
 'greatsword': {'atributo': 'FOR',
                'categoria': 'marcial',
                'dado': '2d6',
                'distancia': False,
                'nome_en': 'Greatsword',
                'nomes_pt': ['espada grande', 'montante']},
 'halberd': {'atributo': 'FOR',
             'categoria': 'marcial',
             'dado': '1d10',
             'distancia': False,
             'nome_en': 'Halberd',
             'nomes_pt': ['alabarda']},
 'handaxe': {'atributo': 'FOR',
             'categoria': 'simples',
             'dado': '1d6',
             'distancia': False,
             'nome_en': 'Handaxe',
             'nomes_pt': ['machadinha']},
 'javelin': {'atributo': 'FOR',
             'categoria': 'simples',
             'dado': '1d6',
             'distancia': False,
             'nome_en': 'Javelin',
             'nomes_pt': ['azagaia']},
 'lance': {'atributo': 'FOR',
           'categoria': 'marcial',
           'dado': '1d12',
           'distancia': False,
           'nome_en': 'Lance',
           'nomes_pt': ['lança montada', 'lança de cavalaria']},
 'light-hammer': {'atributo': 'FOR',
                  'categoria': 'simples',
                  'dado': '1d4',
                  'distancia': False,
                  'nome_en': 'Light hammer',
                  'nomes_pt': ['martelo leve']},
 'longbow': {'atributo': 'DES',
             'categoria': 'marcial',
             'dado': '1d8',
             'distancia': True,
             'nome_en': 'Longbow',
             'nomes_pt': ['arco longo', 'arco']},
 'longsword': {'atributo': 'FOR',
               'categoria': 'marcial',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Longsword',
               'nomes_pt': ['espada longa', 'espada']},
 'mace': {'atributo': 'FOR',
          'categoria': 'simples',
          'dado': '1d6',
          'distancia': False,
          'nome_en': 'Mace',
          'nomes_pt': ['maça']},
 'maul': {'atributo': 'FOR',
          'categoria': 'marcial',
          'dado': '2d6',
          'distancia': False,
          'nome_en': 'Maul',
          'nomes_pt': ['malho', 'marreta']},
 'morningstar': {'atributo': 'FOR',
                 'categoria': 'marcial',
                 'dado': '1d8',
                 'distancia': False,
                 'nome_en': 'Morningstar',
                 'nomes_pt': ['estrela matinal']},
 'net': {'atributo': 'DES',
         'categoria': 'marcial',
         'dado': '1d4',
         'distancia': True,
         'nome_en': 'Net',
         'nomes_pt': ['rede']},
 'pike': {'atributo': 'FOR',
          'categoria': 'marcial',
          'dado': '1d10',
          'distancia': False,
          'nome_en': 'Pike',
          'nomes_pt': ['pique']},
 'quarterstaff': {'atributo': 'FOR',
                  'categoria': 'simples',
                  'dado': '1d6',
                  'distancia': False,
                  'nome_en': 'Quarterstaff',
                  'nomes_pt': ['bordão', 'cajado']},
 'rapier': {'atributo': 'MELHOR',
            'categoria': 'marcial',
            'dado': '1d8',
            'distancia': False,
            'nome_en': 'Rapier',
            'nomes_pt': ['rapieira', 'florete']},
 'scimitar': {'atributo': 'MELHOR',
              'categoria': 'marcial',
              'dado': '1d6',
              'distancia': False,
              'nome_en': 'Scimitar',
              'nomes_pt': ['cimitarra']},
 'shortbow': {'atributo': 'DES',
              'categoria': 'simples',
              'dado': '1d6',
              'distancia': True,
              'nome_en': 'Shortbow',
              'nomes_pt': ['arco curto']},
 'shortsword': {'atributo': 'MELHOR',
                'categoria': 'marcial',
                'dado': '1d6',
                'distancia': False,
                'nome_en': 'Shortsword',
                'nomes_pt': ['espada curta']},
 'sickle': {'atributo': 'FOR',
            'categoria': 'simples',
            'dado': '1d4',
            'distancia': False,
            'nome_en': 'Sickle',
            'nomes_pt': ['foice']},
 'sling': {'atributo': 'DES',
           'categoria': 'simples',
           'dado': '1d4',
           'distancia': True,
           'nome_en': 'Sling',
           'nomes_pt': ['funda']},
 'spear': {'atributo': 'FOR',
           'categoria': 'simples',
           'dado': '1d6',
           'distancia': False,
           'nome_en': 'Spear',
           'nomes_pt': ['lança']},
 'trident': {'atributo': 'FOR',
             'categoria': 'marcial',
             'dado': '1d6',
             'distancia': False,
             'nome_en': 'Trident',
             'nomes_pt': ['tridente']},
 'war-pick': {'atributo': 'FOR',
              'categoria': 'marcial',
              'dado': '1d8',
              'distancia': False,
              'nome_en': 'War pick',
              'nomes_pt': ['picareta de guerra', 'picareta']},
 'warhammer': {'atributo': 'FOR',
               'categoria': 'marcial',
               'dado': '1d8',
               'distancia': False,
               'nome_en': 'Warhammer',
               'nomes_pt': ['martelo de guerra', 'martelo']},
 'whip': {'atributo': 'MELHOR',
          'categoria': 'marcial',
          'dado': '1d4',
          'distancia': False,
          'nome_en': 'Whip',
          'nomes_pt': ['chicote']}}
