"""
Escolhas de equipamento inicial por classe (SRD 5.1).

GERADO por `ingestor/gerar_escolhas_iniciais.py` — NÃO editar à mão.

Cada opção traz `rotulo` (a frase que o Mestre LÊ em voz alta e que a
ficha mostra no botão) e `itens` (o efeito no inventário). Opção de
CATEGORIA traz `categoria` preenchida e `itens` vazio: 'uma arma
marcial' não vira uma lista de 18 nomes numa pergunta falada.
"""

from typing import Any

ESCOLHAS_INICIAIS: dict[str, list[dict[str, Any]]] = {'Bardo': [{'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Rapieira', 'quantidade': 1}],
                        'rotulo': 'Rapieira'},
                       {'categoria': '',
                        'itens': [{'nome': 'Espada longa', 'quantidade': 1}],
                        'rotulo': 'Espada longa'},
                       {'categoria': 'uma arma simples',
                        'itens': [],
                        'rotulo': 'uma arma simples'}]},
           {'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Mochila de diplomata', 'quantidade': 1}],
                        'rotulo': 'Mochila de diplomata'},
                       {'categoria': '',
                        'itens': [{'nome': 'Mochila de artista', 'quantidade': 1}],
                        'rotulo': 'Mochila de artista'}]},
           {'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Alaúde', 'quantidade': 1}],
                        'rotulo': 'Alaúde'},
                       {'categoria': 'um instrumento musical',
                        'itens': [],
                        'rotulo': 'um instrumento musical'}]}],
 'Bruxo': [{'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Besta leve', 'quantidade': 1},
                                  {'nome': 'Virote de besta', 'quantidade': 20}],
                        'rotulo': 'Besta leve, Virote de besta ×20'},
                       {'categoria': 'uma arma simples',
                        'itens': [],
                        'rotulo': 'uma arma simples'}]},
           {'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Bolsa de componentes', 'quantidade': 1}],
                        'rotulo': 'Bolsa de componentes'},
                       {'categoria': 'um foco arcano', 'itens': [], 'rotulo': 'um foco arcano'}]},
           {'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Mochila de estudioso', 'quantidade': 1}],
                        'rotulo': 'Mochila de estudioso'},
                       {'categoria': '',
                        'itens': [{'nome': 'Mochila de masmorra', 'quantidade': 1}],
                        'rotulo': 'Mochila de masmorra'}]},
           {'escolher': 1,
            'opcoes': [{'categoria': 'uma arma simples',
                        'itens': [],
                        'rotulo': 'uma arma simples'}]}],
 'Bárbaro': [{'escolher': 1,
              'opcoes': [{'categoria': '',
                          'itens': [{'nome': 'Machado grande', 'quantidade': 1}],
                          'rotulo': 'Machado grande'},
                         {'categoria': 'uma arma marcial corpo a corpo',
                          'itens': [],
                          'rotulo': 'uma arma marcial corpo a corpo'}]},
             {'escolher': 1,
              'opcoes': [{'categoria': '',
                          'itens': [{'nome': 'Machadinha', 'quantidade': 2}],
                          'rotulo': 'Machadinha ×2'},
                         {'categoria': 'uma arma simples',
                          'itens': [],
                          'rotulo': 'uma arma simples'}]}],
 'Clérigo': [{'escolher': 1,
              'opcoes': [{'categoria': '',
                          'itens': [{'nome': 'Maça', 'quantidade': 1}],
                          'rotulo': 'Maça'},
                         {'categoria': '',
                          'itens': [{'nome': 'Martelo de guerra', 'quantidade': 1}],
                          'rotulo': 'Martelo de guerra'}]},
             {'escolher': 1,
              'opcoes': [{'categoria': '',
                          'itens': [{'nome': 'Cota de escamas', 'quantidade': 1}],
                          'rotulo': 'Cota de escamas'},
                         {'categoria': '',
                          'itens': [{'nome': 'Armadura de couro', 'quantidade': 1}],
                          'rotulo': 'Armadura de couro'},
                         {'categoria': '',
                          'itens': [{'nome': 'Cota de malha', 'quantidade': 1}],
                          'rotulo': 'Cota de malha'}]},
             {'escolher': 1,
              'opcoes': [{'categoria': '',
                          'itens': [{'nome': 'Besta leve', 'quantidade': 1},
                                    {'nome': 'Virote de besta', 'quantidade': 20}],
                          'rotulo': 'Besta leve, Virote de besta ×20'},
                         {'categoria': 'uma arma simples',
                          'itens': [],
                          'rotulo': 'uma arma simples'}]},
             {'escolher': 1,
              'opcoes': [{'categoria': '',
                          'itens': [{'nome': 'Mochila de sacerdote', 'quantidade': 1}],
                          'rotulo': 'Mochila de sacerdote'},
                         {'categoria': '',
                          'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                          'rotulo': 'Mochila de explorador'}]},
             {'escolher': 1,
              'opcoes': [{'categoria': 'um símbolo sagrado',
                          'itens': [],
                          'rotulo': 'um símbolo sagrado'}]}],
 'Druida': [{'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Escudo', 'quantidade': 1}],
                         'rotulo': 'Escudo'},
                        {'categoria': 'uma arma simples',
                         'itens': [],
                         'rotulo': 'uma arma simples'}]},
            {'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Cimitarra', 'quantidade': 1}],
                         'rotulo': 'Cimitarra'},
                        {'categoria': 'uma arma simples corpo a corpo',
                         'itens': [],
                         'rotulo': 'uma arma simples corpo a corpo'}]},
            {'escolher': 1,
             'opcoes': [{'categoria': 'um foco druídico',
                         'itens': [],
                         'rotulo': 'um foco druídico'}]}],
 'Feiticeiro': [{'escolher': 1,
                 'opcoes': [{'categoria': '',
                             'itens': [{'nome': 'Besta leve', 'quantidade': 1},
                                       {'nome': 'Virote de besta', 'quantidade': 20}],
                             'rotulo': 'Besta leve, Virote de besta ×20'},
                            {'categoria': 'uma arma simples',
                             'itens': [],
                             'rotulo': 'uma arma simples'}]},
                {'escolher': 1,
                 'opcoes': [{'categoria': '',
                             'itens': [{'nome': 'Bolsa de componentes', 'quantidade': 1}],
                             'rotulo': 'Bolsa de componentes'},
                            {'categoria': 'um foco arcano',
                             'itens': [],
                             'rotulo': 'um foco arcano'}]},
                {'escolher': 1,
                 'opcoes': [{'categoria': '',
                             'itens': [{'nome': 'Mochila de masmorra', 'quantidade': 1}],
                             'rotulo': 'Mochila de masmorra'},
                            {'categoria': '',
                             'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                             'rotulo': 'Mochila de explorador'}]}],
 'Guerreiro': [{'escolher': 1,
                'opcoes': [{'categoria': '',
                            'itens': [{'nome': 'Cota de malha', 'quantidade': 1}],
                            'rotulo': 'Cota de malha'},
                           {'categoria': '',
                            'itens': [{'nome': 'Armadura de couro', 'quantidade': 1},
                                      {'nome': 'Arco longo', 'quantidade': 1},
                                      {'nome': 'Flecha', 'quantidade': 20}],
                            'rotulo': 'Armadura de couro, Arco longo, Flecha ×20'}]},
               {'escolher': 1,
                'opcoes': [{'categoria': 'uma arma marcial',
                            'itens': [{'nome': 'Escudo', 'quantidade': 1}],
                            'rotulo': 'Escudo, uma arma marcial'},
                           {'categoria': 'uma arma marcial',
                            'itens': [],
                            'rotulo': 'uma arma marcial'}]},
               {'escolher': 1,
                'opcoes': [{'categoria': '',
                            'itens': [{'nome': 'Besta leve', 'quantidade': 1},
                                      {'nome': 'Virote de besta', 'quantidade': 20}],
                            'rotulo': 'Besta leve, Virote de besta ×20'},
                           {'categoria': '',
                            'itens': [{'nome': 'Machadinha', 'quantidade': 2}],
                            'rotulo': 'Machadinha ×2'}]},
               {'escolher': 1,
                'opcoes': [{'categoria': '',
                            'itens': [{'nome': 'Mochila de masmorra', 'quantidade': 1}],
                            'rotulo': 'Mochila de masmorra'},
                           {'categoria': '',
                            'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                            'rotulo': 'Mochila de explorador'}]}],
 'Ladino': [{'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Rapieira', 'quantidade': 1}],
                         'rotulo': 'Rapieira'},
                        {'categoria': '',
                         'itens': [{'nome': 'Espada curta', 'quantidade': 1}],
                         'rotulo': 'Espada curta'}]},
            {'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Arco curto', 'quantidade': 1},
                                   {'nome': 'Flecha', 'quantidade': 20}],
                         'rotulo': 'Arco curto, Flecha ×20'},
                        {'categoria': '',
                         'itens': [{'nome': 'Espada curta', 'quantidade': 1}],
                         'rotulo': 'Espada curta'}]},
            {'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Mochila de gatuno', 'quantidade': 1}],
                         'rotulo': 'Mochila de gatuno'},
                        {'categoria': '',
                         'itens': [{'nome': 'Mochila de masmorra', 'quantidade': 1}],
                         'rotulo': 'Mochila de masmorra'},
                        {'categoria': '',
                         'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                         'rotulo': 'Mochila de explorador'}]}],
 'Mago': [{'escolher': 1,
           'opcoes': [{'categoria': '',
                       'itens': [{'nome': 'Bordão', 'quantidade': 1}],
                       'rotulo': 'Bordão'},
                      {'categoria': '',
                       'itens': [{'nome': 'Adaga', 'quantidade': 1}],
                       'rotulo': 'Adaga'}]},
          {'escolher': 1,
           'opcoes': [{'categoria': '',
                       'itens': [{'nome': 'Bolsa de componentes', 'quantidade': 1}],
                       'rotulo': 'Bolsa de componentes'},
                      {'categoria': 'um foco arcano', 'itens': [], 'rotulo': 'um foco arcano'}]},
          {'escolher': 1,
           'opcoes': [{'categoria': '',
                       'itens': [{'nome': 'Mochila de estudioso', 'quantidade': 1}],
                       'rotulo': 'Mochila de estudioso'},
                      {'categoria': '',
                       'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                       'rotulo': 'Mochila de explorador'}]}],
 'Monge': [{'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Espada curta', 'quantidade': 1}],
                        'rotulo': 'Espada curta'},
                       {'categoria': 'uma arma simples',
                        'itens': [],
                        'rotulo': 'uma arma simples'}]},
           {'escolher': 1,
            'opcoes': [{'categoria': '',
                        'itens': [{'nome': 'Mochila de masmorra', 'quantidade': 1}],
                        'rotulo': 'Mochila de masmorra'},
                       {'categoria': '',
                        'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                        'rotulo': 'Mochila de explorador'}]}],
 'Paladino': [{'escolher': 1,
               'opcoes': [{'categoria': 'uma arma marcial',
                           'itens': [{'nome': 'Escudo', 'quantidade': 1}],
                           'rotulo': 'Escudo, uma arma marcial'},
                          {'categoria': 'uma arma marcial',
                           'itens': [],
                           'rotulo': 'uma arma marcial'}]},
              {'escolher': 1,
               'opcoes': [{'categoria': '',
                           'itens': [{'nome': 'Azagaia', 'quantidade': 5}],
                           'rotulo': 'Azagaia ×5'},
                          {'categoria': 'uma arma simples',
                           'itens': [],
                           'rotulo': 'uma arma simples'}]},
              {'escolher': 1,
               'opcoes': [{'categoria': '',
                           'itens': [{'nome': 'Mochila de sacerdote', 'quantidade': 1}],
                           'rotulo': 'Mochila de sacerdote'},
                          {'categoria': '',
                           'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                           'rotulo': 'Mochila de explorador'}]},
              {'escolher': 1,
               'opcoes': [{'categoria': 'um símbolo sagrado',
                           'itens': [],
                           'rotulo': 'um símbolo sagrado'}]}],
 'Ranger': [{'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Cota de escamas', 'quantidade': 1}],
                         'rotulo': 'Cota de escamas'},
                        {'categoria': '',
                         'itens': [{'nome': 'Armadura de couro', 'quantidade': 1}],
                         'rotulo': 'Armadura de couro'}]},
            {'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Espada curta', 'quantidade': 2}],
                         'rotulo': 'Espada curta ×2'},
                        {'categoria': 'uma arma simples corpo a corpo',
                         'itens': [],
                         'rotulo': 'uma arma simples corpo a corpo'}]},
            {'escolher': 1,
             'opcoes': [{'categoria': '',
                         'itens': [{'nome': 'Mochila de masmorra', 'quantidade': 1}],
                         'rotulo': 'Mochila de masmorra'},
                        {'categoria': '',
                         'itens': [{'nome': 'Mochila de explorador', 'quantidade': 1}],
                         'rotulo': 'Mochila de explorador'}]}]}
